/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "i2c.h"
#include "usart.h"
#include "gpio.h"
#include "ina228_driver.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */

/* ================= USER DEFINES ================= */
#define RX_BUF_SIZE    64
#define MAX_SAMPLES    2000
/* =============================================== */

/* UART receive buffer */
static char rxBuf[RX_BUF_SIZE];
static int  rxIndex;

/* Sampling parameters */
static int sampling_rate = 0;   // Hz
static int total_time    = 0;   // seconds
static int num_samples   = 0;

/* Data buffers */
static float voltage_buf1[MAX_SAMPLES];
static float current_buf1[MAX_SAMPLES];
static float power_buf1[MAX_SAMPLES];

static float voltage_buf2[MAX_SAMPLES];
static float current_buf2[MAX_SAMPLES];
static float power_buf2[MAX_SAMPLES];

int main(void)
{
  /* HAL initialization */
  HAL_Init();
  SystemClock_Config();

  /* Initialize peripherals generated by CubeMX */
  MX_GPIO_Init();
  MX_I2C1_Init();
  MX_USART2_UART_Init();

  /* Set GPIO outputs PB0, PB1, PB2 LOW */
  HAL_GPIO_WritePin(GPIOB,
                    GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2,
                    GPIO_PIN_RESET);

  /* Initialize both INA228 sensors */
  if (INA228_Init(INA228_ADDR1, 0.01f) != HAL_OK)
  {
    const char *msg = "INA228 #1 INIT FAILED\n";
    HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);
  }
  if (INA228_Init(INA228_ADDR2, 0.01f) != HAL_OK)
  {
    const char *msg = "INA228 #2 INIT FAILED\n";
    HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);
  }

  /* ================= Main loop ================= */
  while (1)
  {
    UART_ReceiveLine();

    if (Parse_Command())
    {
      const char ok[] = "OK\n";
      HAL_UART_Transmit(&huart2, (uint8_t*)ok, sizeof(ok)-1, HAL_MAX_DELAY);

      Acquire_Data();
      Transmit_Data();
      //Transmit_Data_Test();
    }
    else
    {
      const char err[] = "ERR\n";
      HAL_UART_Transmit(&huart2, (uint8_t*)err, sizeof(err)-1, HAL_MAX_DELAY);
    }
  }
}

/* ========================================================= */
/* Receive one UART line terminated by '\n'                  */
/* ========================================================= */
static void UART_ReceiveLine(void)
{
  rxIndex = 0;
  memset(rxBuf, 0, sizeof(rxBuf));

  while (1)
  {
    uint8_t byte;
    HAL_UART_Receive(&huart2, &byte, 1, HAL_MAX_DELAY);

    if (byte == '\n')
      break;

    if (rxIndex < RX_BUF_SIZE - 1)
      rxBuf[rxIndex++] = (char)byte;
  }
}

/* ========================================================= */
/* Parse: START,<sampling_rate>,<total_time>                 */
/* ========================================================= */
static int Parse_Command(void)
{
  if (strncmp(rxBuf, "START", 5) != 0)
    return 0;

  char *tok = strtok(rxBuf, ",");   // START
  tok = strtok(NULL, ",");
  if (!tok) return 0;
  sampling_rate = atoi(tok);

  tok = strtok(NULL, ",");
  if (!tok) return 0;
  total_time = atoi(tok);

  if (sampling_rate <= 0 || total_time <= 0)
    return 0;

  num_samples = sampling_rate * total_time;
  if (num_samples > MAX_SAMPLES)
    num_samples = MAX_SAMPLES;

  return 1;
}

/* ========================================================= */
/* Acquire data from INA228                                  */
/* ========================================================= */
static void Acquire_Data(void)
{
  uint8_t healthy1 = 0, healthy2 = 0;
  INA228_CheckHealth(INA228_ADDR1, &healthy1);
  INA228_CheckHealth(INA228_ADDR2, &healthy2);

  if (!healthy1 || !healthy2)
  {
    for (int i = 0; i < num_samples; i++) {
    	voltage_buf1[i] = current_buf1[i] = power_buf1[i] = 0.0f;
    	voltage_buf2[i] = current_buf2[i] = power_buf2[i] = 0.0f;
    }
    return;
  }

  uint32_t delay_ms = (sampling_rate > 0) ? (1000 / sampling_rate) : 1;

  for (int i = 0; i < num_samples; i++)
  {
    float v1 = 0.0f, c1 = 0.0f, p1 = 0.0f;
    float v2 = 0.0f, c2 = 0.0f, p2 = 0.0f;

    INA228_ReadVoltage(INA228_ADDR1, &v1);
    INA228_ReadCurrent(INA228_ADDR1, &c1);
    INA228_ReadPower  (INA228_ADDR1, &p1);

    INA228_ReadVoltage(INA228_ADDR2, &v2);
    INA228_ReadCurrent(INA228_ADDR2, &c2);
    INA228_ReadPower  (INA228_ADDR2, &p2);

    voltage_buf1[i] = v1;
    current_buf1[i] = c1;
    power_buf1[i]   = p1;

    voltage_buf2[i] = v2;
    current_buf2[i] = c2;
    power_buf2[i]   = p2;

    HAL_Delay(delay_ms);
  }
}

/* ========================================================= */
/* Transmit data from both sensors to PC                     */
/* Format: v1,c1,p1,v2,c2,p2                                 */
/* ========================================================= */
static void Transmit_Data(void)
{
  char line[RX_BUF_SIZE];

  for (int i = 0; i < num_samples; i++)
  {
    int len = snprintf(line, sizeof(line),
                       "%.6f,%.6f,%.6f,%.6f,%.6f,%.6f\n",
                       voltage_buf1[i],
                       current_buf1[i],
                       power_buf1[i],
					   voltage_buf2[i],
                       current_buf2[i],
                       power_buf2[i]);

    HAL_UART_Transmit(&huart2, (uint8_t*)line, len, HAL_MAX_DELAY);
  }

  const char done[] = "DONE\n";
  HAL_UART_Transmit(&huart2, (uint8_t*)done, sizeof(done)-1, HAL_MAX_DELAY);
}

/* ========================================================= */
static void Transmit_Data_Test(void)
{
  char line[64];
  float test_x=1.5;
  float test_y=10;
  float test_power=test_x*test_y;
  for (int i = 0; i < num_samples; i++)
  {
	  test_x+=0.1;
	  test_y+=0.45;
	  test_power=test_x*test_y;
    int len = snprintf(line, sizeof(line),
                       "%.6f,%.6f,%.6f\n",
                       test_x,
                       test_y,
                       test_power);

    HAL_UART_Transmit(&huart2, (uint8_t*)line, len, HAL_MAX_DELAY);
  }

  const char done[] = "DONE\n";
  HAL_UART_Transmit(&huart2, (uint8_t*)done, sizeof(done)-1, HAL_MAX_DELAY);
}
/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
	RCC_OscInitTypeDef RCC_OscInitStruct = {0};
	RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

	__HAL_RCC_PWR_CLK_ENABLE();
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
	RCC_OscInitStruct.HSIState = RCC_HSI_ON;
	RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
	HAL_RCC_OscConfig(&RCC_OscInitStruct);

	RCC_ClkInitStruct.ClockType =
	RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
	RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;

	RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_HSI;
	RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

	HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0);
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */

void Error_Handler(void)
{
	;
}
